# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    defaults:
      run:
        working-directory: SharpSevenZip

    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        framework:
          - netstandard2.0
          - net6.0
          - net8.0
          - net48
        include:
          - sdk: 8.0.x
          - framework: net6.0
            sdk: 6.0.x

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.sdk }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -f ${{ matrix.framework }} --no-restore
    - name: check suppor sfn
      run: fsutil behavior query disable8dot3
    - name: Test
      run: dotnet test -f ${{ matrix.framework }} --no-build --verbosity normal
