# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    defaults:
      run:
        working-directory: SharpSevenZip

    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        arch: [ x64, x86 ]
        framework:
          - netstandard2.0
          - net6.0
          - net8.0
          - net48
        include:
          - sdk: 8.0.x
          - framework: net6.0
            sdk: 6.0.x

    runs-on: ${{ matrix.os }}

    steps:
    - name: Enable SFN
      run: fsutil behavior set disable8dot3 0
      working-directory: .
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.sdk }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build SharpSevenZip/SharpSevenZip.csproj -c Release -f ${{ matrix.framework }} -p:Platform=${{ matrix.arch }} --no-restore
    - name: Build (test)
      if: ${{ !contains(fromJson('["netstandard2.0"]'), matrix.framework) }}
      run: |
        dotnet build SharpSevenZip.Tests/SharpSevenZip.Tests.csproj -c Release -f ${{ matrix.framework }} -p:Platform=${{ matrix.arch }} --no-restore
        dotnet build SharpSevenZipBenchmarks/SharpSevenZipBenchmarks.csproj -c Release -f ${{ matrix.framework }} -p:Platform=${{ matrix.arch }} --no-restore
    - name: Test
      run: dotnet test -c Release -f ${{ matrix.framework }} -p:Platform=${{ matrix.arch }} --no-build --verbosity normal
